# Generated by Django 2.1.2 on 2018-10-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='/static/blog/imagenes/D059BC4A-CCF3-4495-849ABBAFAED10456.jpg', upload_to='static/upImg/'),
        ),
    ]
