# Generated by Django 2.1.2 on 2018-10-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181024_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.CharField(choices=[('Rescatado', 'Rescatado'), ('Disponible', 'Disponible'), ('Disponible', 'Adoptado')], default='Rescatado', max_length=2),
        ),
    ]
