# Generated by Django 2.1.2 on 2018-10-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181024_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.CharField(choices=[('RE', 'Rescatado'), ('AV', 'Disponible'), ('AD', 'Adoptado')], default='RE', max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(default='RE', max_length=100),
        ),
    ]
