# Generated by Django 2.1.2 on 2018-10-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181024_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.TextField(choices=[('RE', 'Rescatado'), ('AV', 'Disponible'), ('AD', 'Adoptado')], default='RE'),
        ),
    ]
